// User Actions
export const SET_USER = "SET_USER";
export const TOGGLE_AUTHENTICATING = "TOGGLE_AUTHENTICATING";
export const LOGOUT_USER = "LOGOUT_USER";

// Data actions

export const SET_PUBLIC_POSTS = "SET_PUBLIC_POSTS";
export const TOGGLE_PUBLIC_POSTS_FETCHING =
	"TOGGLE_TOGGLE_PUBLIC_POSTS_FETCHING";

export const UPLOAD_POSTS = "UPLOAD_POSTS";
export const TOGGLE_POSTS_UPLOADING = "TOGGLE_POSTS_UPLOADING";
